language: minimal
jobs:
  include:
    - stage: validate
      env:
        - TEST=validate
      script:
        - curl -fsSL https://raw.githubusercontent.com/nemchik/ShellSuite/master/shellsuite.sh -o shellsuite.sh && bash shellsuite.sh -p "${PWD}" -v "bashate" -f " -i E006"
        - curl -fsSL https://raw.githubusercontent.com/nemchik/ShellSuite/master/shellsuite.sh -o shellsuite.sh && bash shellsuite.sh -p "${PWD}" -v "shellcheck" -f " -x"
        - curl -fsSL https://raw.githubusercontent.com/nemchik/ShellSuite/master/shellsuite.sh -o shellsuite.sh && bash shellsuite.sh -p "${PWD}" -v "shfmt" -f " -s -i 4 -ci -sr -d"
    - stage: run
      env: TEST=run_install
      script: sudo bash ./main.sh -t ${TEST}
    - stage: run
      env: TEST=run_generate_slim
      script: sudo bash ./main.sh -t ${TEST}
    - stage: run
      env: TEST=run_generate_full
      script: sudo bash ./main.sh -t ${TEST}
matrix:
  fast_finish: true
  allow_failures:
    - stage: run
      env: TEST=run_generate_full
      script: sudo bash ./main.sh -t ${TEST}
