dist: trusty
language: generic
sudo: required
group: travis_latest
jobs:
  include:
  - stage: validate
    script:
    - sudo bash ./main.sh -t validate_newline
    - sudo bash ./main.sh -t validate_bashate
    - sudo bash ./main.sh -t validate_shellcheck
  - stage: run
    script: sudo bash ./main.sh -t run_install
  - stage: run
    script: sudo bash ./main.sh -t run_generate
  - stage: run
    script: sudo bash ./main.sh -t run_generate_full
matrix:
  fast_finish: true
  allow_failures:
  - stage: run
    script: sudo bash ./main.sh -t run_generate_full
