site_name: DockSTARTer
site_url: https://dockstarter.com
site_author: GhostWriters
site_description: DockSTARTer helps you get started with home server apps running in Docker.

repo_name: GhostWriters/DockSTARTer
repo_url: https://github.com/GhostWriters/DockSTARTer

copyright: Copyright &copy; 2023 GhostWriters

theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/favicon.ico
  logo: assets/icon.png

extra:
  analytics:
    provider: google
    property: G-QVNLHE95FS
  social:
    - icon: fontawesome/brands/discord
      link: https://dockstarter.com/discord
    - icon: fontawesome/brands/github
      link: https://github.com/GhostWriters/DockSTARTer

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.escapeall
  - pymdownx.extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        advanced/overrides.md: https://dockstarter.com/overrides/introduction/
        apps/hydra2.md: https://dockstarter.com/apps/nzbhydra2/
        apps/letsencrypt.md: https://dockstarter.com/apps/swag/
        apps/minecraft_bedrock_server.md: https://dockstarter.com/apps/minecraftbedrockserver/
        apps/minecraft_server.md: https://dockstarter.com/apps/minecraftserver/
        apps/mylar.md: https://dockstarter.com/apps/mylar3/
        apps/plexrequests.md: https://dockstarter.com/apps/ombi/
        apps/sickrage.md: https://dockstarter.com/apps/sickchill/
        apps/ttrss.md: https://dockstarter.com/apps/freshrss/
        apps/unifi.md: https://dockstarter.com/apps/unificontroller/
        apps/vaultwarden.md: https://dockstarter.com/apps/bitwarden/
        discord.md: https://discord.gg/xR3cyUb
        overrides/fireflyiii.md: https://dockstarter.com/apps/fireflyiii/
        overrides/kitana.md: https://dockstarter.com/apps/kitana/
        overrides/overseerr.md: https://dockstarter.com/apps/overseerr/
        overrides/petio.md: https://dockstarter.com/apps/petio/
        overrides/requestrr.md: https://dockstarter.com/apps/requestrr/
  - search

nav:
  - Home: index.md
  - introduction.md
  - Basics:
      - basics/available-apps.md
      - basics/command-line-usage.md
      - basics/env-var-info.md
      - basics/faq.md
      - basics/migration.md
      - basics/port-conflicts.md
      - basics/support.md
  - Advanced:
      - advanced/backups.md
      - advanced/domain-info.md
      - advanced/macvlan.md
      - advanced/openmediavault.md
      - advanced/smb-mounting.md
      - advanced/technical-info.md
      - advanced/uninstall.md
      - advanced/vpn-info.md
  - App Specifics:
      - apps/adguard.md
      - apps/adminer.md
      - apps/airsonicadvanced.md
      - apps/amd.md
      - apps/apcupsd.md
      - apps/apprise.md
      - apps/audiobookshelf.md
      - apps/autobrr.md
      - apps/azuracast.md
      - apps/bazarr.md
      - apps/beets.md
      - apps/bitwarden.md
      - apps/booksonicair.md
      - apps/bookstack.md
      - apps/calibre.md
      - apps/calibreweb.md
      - apps/cloudcmd.md
      - apps/cloudflareddns.md
      - apps/codeserver.md
      - apps/dasshio.md
      - apps/ddclient.md
      - apps/deemix.md
      - apps/deluge.md
      - apps/delugevpn.md
      - apps/doplarr.md
      - apps/dozzle.md
      - apps/duckdns.md
      - apps/duplicacy.md
      - apps/duplicati.md
      - apps/emby.md
      - apps/fail2ban.md
      - apps/filebot.md
      - apps/filebrowser.md
      - apps/fireflyiii.md
      - apps/flame.md
      - apps/flaresolverr.md
      - apps/freshrss.md
      - apps/gitea.md
      - apps/glances.md
      - apps/gluetun.md
      - apps/goaccess.md
      - apps/grafana.md
      - apps/grocy.md
      - apps/guacamole.md
      - apps/h5ai.md
      - apps/handbrake.md
      - apps/headphones.md
      - apps/heimdall.md
      - apps/homeassistant.md
      - apps/homebridge.md
      - apps/homepage.md
      - apps/homer.md
      - apps/htpcmanager.md
      - apps/httpserver.md
      - apps/huginn.md
      - apps/influxdb.md
      - apps/jackett.md
      - apps/jellyfin.md
      - apps/jellyseerr.md
      - apps/jfago.md
      - apps/kanboard.md
      - apps/kitana.md
      - apps/kiwixserve.md
      - apps/komga.md
      - apps/lazylibrarian.md
      - apps/ldapauth.md
      - apps/librespeed.md
      - apps/lidarr.md
      - apps/limnoria.md
      - apps/logarr.md
      - apps/logitechmediaserver.md
      - apps/lyrionmusicserver.md
      - apps/makemkv.md
      - apps/mariadb.md
      - apps/medusa.md
      - apps/minecraftbedrockserver.md
      - apps/minecraftserver.md
      - apps/monitorr.md
      - apps/mosquitto.md
      - apps/moviematch.md
      - apps/murmur.md
      - apps/mylar3.md
      - apps/netdata.md
      - apps/nextcloud.md
      - apps/nodered.md
      - apps/nzbget.md
      - apps/nzbgetvpn.md
      - apps/nzbhydra2.md
      - apps/omadacontroller.md
      - apps/ombi.md
      - apps/openldap.md
      - apps/openspeedtest.md
      - apps/openvpnas.md
      - apps/organizr.md
      - apps/overseerr.md
      - apps/petio.md
      - apps/pgadmin.md
      - apps/pgbackup.md
      - apps/photostructure.md
      - apps/phpmyadmin.md
      - apps/picard.md
      - apps/pihole.md
      - apps/piwigo.md
      - apps/plex.md
      - apps/plexanisync.md
      - apps/portainer.md
      - apps/portaineragent.md
      - apps/postgres.md
      - apps/privoxyvpn.md
      - apps/prometheus.md
      - apps/prowlarr.md
      - apps/pyload.md
      - apps/qbittorrent.md
      - apps/qbittorrentvpn.md
      - apps/quasselcore.md
      - apps/quasselweb.md
      - apps/radarr.md
      - apps/readarr.md
      - apps/recyclarr.md
      - apps/requestrr.md
      - apps/resiliosync.md
      - apps/rsnapshot.md
      - apps/rustdesk.md
      - apps/rutorrent.md
      - apps/sabnzbd.md
      - apps/sabnzbdvpn.md
      - apps/sickchill.md
      - apps/smokeping.md
      - apps/sonarr.md
      - apps/speedtest.md
      - apps/swag.md
      - apps/synclounge.md
      - apps/syncthing.md
      - apps/tandoor.md
      - apps/tautulli.md
      - apps/tdarr.md
      - apps/tdarrnode.md
      - apps/telegraf.md
      - apps/thelounge.md
      - apps/timemachine.md
      - apps/traefik.md
      - apps/traktarr.md
      - apps/transmission.md
      - apps/transmissionvpn.md
      - apps/tvheadend.md
      - apps/ubooquity.md
      - apps/unificontroller.md
      - apps/unmanic.md
      - apps/unpackerr.md
      - apps/uptimekuma.md
      - apps/varken.md
      - apps/vsftpd.md
      - apps/watchtower.md
      - apps/wireguard.md
      - apps/xbackbone.md
      - apps/xteve.md
      - apps/yacht.md
      - apps/youtubedl.md
      - apps/znc.md
  - Overrides:
      - overrides/introduction.md
      - overrides/autoscan.md
      - overrides/bw_plex.md
      - overrides/conreq.md
      - overrides/dashmachine.md
      - overrides/nginxproxymanager.md
      - overrides/plpp.md
      - overrides/yacreader.md
