site_name: DockSTARTer
site_url: https://dockstarter.com
site_author: GhostWriters
site_description: DockSTARTer helps you get started with home server apps running in Docker.

repo_name: GhostWriters/DockSTARTer
repo_url: https://github.com/GhostWriters/DockSTARTer

copyright: Copyright &copy; 2023 GhostWriters

theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/favicon.ico
  logo: assets/icon.png

extra:
  analytics:
    provider: google
    property: G-QVNLHE95FS
  social:
    - icon: fontawesome/brands/discord
      link: https://dockstarter.com/discord
    - icon: fontawesome/brands/github
      link: https://github.com/GhostWriters/DockSTARTer
  status:
    deprecated: This application is deprecated. Use at your own risk.

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.escapeall
  - pymdownx.extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

exclude_docs: |
  apps/

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - include_dir_to_nav
  - minify:
      minify_html: true
  - multirepo:
      cleanup: true
      keep_docs_dir: false
      nav_repos:
        - name: apps
          import_url: https://github.com/GhostWriters/DockSTARTer-Templates?branch=main
          imports: [docs/apps/*]
  - redirects:
      redirect_maps:
        advanced/overrides.md: https://dockstarter.com/overrides/introduction/
        apps/hydra2.md: https://dockstarter.com/apps/nzbhydra2/
        apps/letsencrypt.md: https://dockstarter.com/apps/swag/
        apps/minecraft_bedrock_server.md: https://dockstarter.com/apps/minecraftbedrockserver/
        apps/minecraft_server.md: https://dockstarter.com/apps/minecraftserver/
        apps/mylar.md: https://dockstarter.com/apps/mylar3/
        apps/plexrequests.md: https://dockstarter.com/apps/ombi/
        apps/sickrage.md: https://dockstarter.com/apps/sickchill/
        apps/ttrss.md: https://dockstarter.com/apps/freshrss/
        apps/unifi.md: https://dockstarter.com/apps/unificontroller/
        apps/vaultwarden.md: https://dockstarter.com/apps/bitwarden/
        discord.md: https://discord.gg/xR3cyUb
        overrides/fireflyiii.md: https://dockstarter.com/apps/fireflyiii/
        overrides/kitana.md: https://dockstarter.com/apps/kitana/
        overrides/overseerr.md: https://dockstarter.com/apps/overseerr/
        overrides/petio.md: https://dockstarter.com/apps/petio/
        overrides/requestrr.md: https://dockstarter.com/apps/requestrr/
  - search

nav:
  - Home: README.md
  - introduction.md
  - Basics:
      - basics/available-apps.md
      - basics/command-line-usage.md
      - basics/env-var-info.md
      - basics/faq.md
      - basics/migration.md
      - basics/port-conflicts.md
      - basics/support.md
  - Advanced:
      - advanced/backups.md
      - advanced/domain-info.md
      - advanced/macvlan.md
      - advanced/openmediavault.md
      - advanced/smb-mounting.md
      - advanced/technical-info.md
      - advanced/uninstall.md
      - advanced/vpn-info.md
  - App Specifics:
      - apps
  - Overrides:
      - overrides/introduction.md
      - overrides/autoscan.md
      - overrides/bw_plex.md
      - overrides/conreq.md
      - overrides/dashmachine.md
      - overrides/nginxproxymanager.md
      - overrides/plpp.md
      - overrides/yacreader.md
