---
site_name: DockSTARTer
site_description: DockSTARTer helps you get started with home server apps running in Docker.
site_author: GhostWriters
site_url: https://dockstarter.com

repo_url: https://github.com/GhostWriters/DockSTARTer
repo_name: GhostWriters/DockSTARTer

copyright: Copyright &copy; 2021 GhostWriters

extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/discord
      link: https://dockstarter.com/discord
    - icon: fontawesome/brands/github-square
      link: https://github.com/GhostWriters/DockSTARTer

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - redirects:
      redirect_maps:
        advanced/overrides.md: https://dockstarter.com/overrides/introduction
        apps/hydra2.md: https://dockstarter.com/apps/nzbhydra2/
        apps/letsencrypt.md: https://dockstarter.com/apps/swag/
        apps/mylar.md: https://dockstarter.com/apps/mylar3/
        apps/plexrequests.md: https://dockstarter.com/apps/ombi/
        apps/sickrage.md: https://dockstarter.com/apps/sickchill/
        apps/ttrss.md: https://dockstarter.com/apps/freshrss/
        apps/unifi.md: https://dockstarter.com/apps/unificontroller/
        discord.md: https://discord.gg/xR3cyUb

theme:
  name: material
  features:
    - navigation.instant
  language: en
  favicon: images/favicon.ico
  logo: images/icon.png
  palette:
    primary: blue grey
    accent: indigo

nav:
  - Home: index.md
  - introduction.md
  - Basics:
      - basics/available-apps.md
      - basics/command-line-usage.md
      - basics/env-var-info.md
      - basics/faq.md
      - basics/migration.md
      - basics/port-conflicts.md
      - basics/support.md
  - Advanced:
      - advanced/backups.md
      - advanced/domain-info.md
      - advanced/macvlan.md
      - advanced/openmediavault.md
      - advanced/smb-mounting.md
      - advanced/technical-info.md
      - advanced/uninstall.md
      - advanced/vpn-info.md
  - App Specifics:
      - apps/adguard.md
      - apps/airdcpp.md
      - apps/airsonic.md
      - apps/amd.md
      - apps/apcupsd.md
      - apps/bazarr.md
      - apps/beets.md
      - apps/bitwarden.md
      - apps/booksonic.md
      - apps/bookstack.md
      - apps/calibre.md
      - apps/calibreweb.md
      - apps/cloudcmd.md
      - apps/cloudflareddns.md
      - apps/codeserver.md
      - apps/couchpotato.md
      - apps/dasshio.md
      - apps/ddclient.md
      - apps/deemix.md
      - apps/deluge.md
      - apps/delugevpn.md
      - apps/dozzle.md
      - apps/duckdns.md
      - apps/duplicacy.md
      - apps/duplicati.md
      - apps/emby.md
      - apps/filebot.md
      - apps/filebrowser.md
      - apps/flaresolverr.md
      - apps/freshrss.md
      - apps/glances.md
      - apps/goaccess.md
      - apps/grafana.md
      - apps/grocy.md
      - apps/guacamole.md
      - apps/h5ai.md
      - apps/handbrake.md
      - apps/headphones.md
      - apps/heimdall.md
      - apps/homeassistant.md
      - apps/htpcmanager.md
      - apps/httpserver.md
      - apps/huginn.md
      - apps/influxdb.md
      - apps/jackett.md
      - apps/jellyfin.md
      - apps/jfago.md
      - apps/kiwixserve.md
      - apps/lazylibrarian.md
      - apps/ldapauth.md
      - apps/librespeed.md
      - apps/lidarr.md
      - apps/limnoria.md
      - apps/logarr.md
      - apps/logitechmediaserver.md
      - apps/makemkv.md
      - apps/mariadb.md
      - apps/mcmyadmin2.md
      - apps/medusa.md
      - apps/minecraft_bedrock_server.md
      - apps/minecraft_server.md
      - apps/monitorr.md
      - apps/mosquitto.md
      - apps/moviematch.md
      - apps/murmur.md
      - apps/muximux.md
      - apps/mylar3.md
      - apps/netdata.md
      - apps/nextcloud.md
      - apps/nodered.md
      - apps/nzbget.md
      - apps/nzbgetvpn.md
      - apps/nzbhydra2.md
      - apps/ombi.md
      - apps/omadacontroller.md
      - apps/openldap.md
      - apps/openvpnas.md
      - apps/organizr.md
      - apps/ouroboros.md
      - apps/photoshow.md
      - apps/photostructure.md
      - apps/phpmyadmin.md
      - apps/picard.md
      - apps/pihole.md
      - apps/piwigo.md
      - apps/plex.md
      - apps/plexanisync.md
      - apps/portainer.md
      - apps/portaineragent.md
      - apps/prometheus.md
      - apps/pyload.md
      - apps/qbittorrent.md
      - apps/qbittorrentvpn.md
      - apps/quasselcore.md
      - apps/quasselweb.md
      - apps/radarr.md
      - apps/requestrr.md
      - apps/resiliosync.md
      - apps/rsnapshot.md
      - apps/rtorrentvpn.md
      - apps/rutorrent.md
      - apps/sabnzbd.md
      - apps/sabnzbdvpn.md
      - apps/samba.md
      - apps/sickchill.md
      - apps/sickrage.md
      - apps/smokeping.md
      - apps/sonarr.md
      - apps/speedtest.md
      - apps/swag.md
      - apps/synclounge.md
      - apps/syncthing.md
      - apps/tautulli.md
      - apps/tdarr.md
      - apps/tdarrnode.md
      - apps/telegraf.md
      - apps/thelounge.md
      - apps/traktarr.md
      - apps/transmission.md
      - apps/transmissionvpn.md
      - apps/tvheadend.md
      - apps/ubooquity.md
      - apps/unificontroller.md
      - apps/unmanic.md
      - apps/unpackerr.md
      - apps/varken.md
      - apps/vsftpd.md
      - apps/watchtower.md
      - apps/wireguard.md
      - apps/xbackbone.md
      - apps/xteve.md
      - apps/yacht.md
      - apps/youtubedl.md
      - apps/znc.md
  - Overrides:
      - overrides/introduction.md
      - overrides/autoscan.md
      - overrides/bw_plex.md
      - overrides/conreq.md
      - overrides/dashmachine.md
      - overrides/fireflyiii.md
      - overrides/kitana.md
      - overrides/nginxproxymanager.md
      - overrides/overseerr.md
      - overrides/petio.md
      - overrides/plpp.md
      - overrides/requestrr.md
      - overrides/yacreader.md
