services:
  grafana:
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=${GRAFANA_GF_INSTALL_PLUGINS}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    user: ${PUID}:${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/grafana:/var/lib/grafana
      - ${DOCKERSTORAGEDIR}:/storage
