#/APPNICENAME=Grafana
#/APPDESCRIPTION=Metrics dashboard and graph editor
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=${GRAFANA_GF_INSTALL_PLUGINS}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/grafana:/var/lib/grafana
      - ${DOCKERSHAREDDIR}:/shared
    user: ${PUID}
