name: "Label PRs from globs"
on:
  schedule:
  - cron: "0 * * * *"
  workflow_run:
    workflows: ["Label Trigger"]


jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v1.1.0
        with:
          jobs: 'pr-labeler'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
