name: Lint

on:
  push:
  pull_request:

jobs:
  editorconfig-checker:
    runs-on: ubuntu-latest
    container:
      image: mstruebing/editorconfig-checker:v3.6.0@sha256:3fee6fe35c9ec21367b92ca50b3bea856ffc8a7a186044c329ac8bb23b33284a
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: editorconfig-checker
        run: editorconfig-checker .

  markdownlint:
    runs-on: ubuntu-latest
    container:
      image: davidanson/markdownlint-cli2:v0.20.0@sha256:8f7487027e6786a583da1c8be8b0541bbd17582a4b8fbe3e27a29d9f29fa77d0
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: markdownlint
        run: markdownlint-cli2 **.{md,markdown}

  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck-alpine:v0.11.0@sha256:9955be09ea7f0dbf7ae942ac1f2094355bb30d96fffba0ec09f5432207544002
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: install alpine packages
        run: apk add --no-cache findutils
      - name: shellcheck
        run: find . -name '*.sh' -exec shellcheck {} +

  shfmt:
    runs-on: ubuntu-latest
    container:
      image: mvdan/shfmt:v3.12.0-alpine@sha256:204a4d2d876123342ad394bd9a28fb91e165abc03868790d4b39cfa73233f150
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: install alpine packages
        run: apk add --no-cache findutils
      - name: shfmt
        run: find . -name '*.sh' -exec shfmt -d {} +

  yamllint:
    runs-on: ubuntu-latest
    container:
      image: peterdavehello/yamllint:1.37.0@sha256:bb8e9a2970f31503714447e2c309add8eb27ad57a66dee6fa2d37322415ed0ae
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: yamllint
        run: yamllint .
