name: Lint

on: [push, pull_request]

jobs:

  editorconfig-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: editorconfig-checker
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}:/check mstruebing/editorconfig-checker

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: markdownlint
        run: |
          find ~+ ${github_workspace} -name '*.md' | xargs docker run --rm -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} markdownlint/markdownlint -r ~MD013,~MD033,~MD034

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        run: |
          find ~+ ${github_workspace} -name '*.sh' | xargs docker run --rm -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} koalaman/shellcheck

  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shfmt
        run: |
          find ~+ ${github_workspace} -name '*.sh' | xargs docker run --rm -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} mvdan/shfmt -s -d

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        run: |
          find ~+ ${github_workspace} -name '*.yaml' -o -name '*.yml' | xargs docker run --rm -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} peterdavehello/yamllint yamllint -d '{extends: default, rules: {document-start: {present: false}, line-length: disable}}'
